# Generated by Django 3.0.5 on 2020-04-24 05:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OfferTypes',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
            ],
            options={
                'verbose_name': 'тип предложения',
                'verbose_name_plural': 'тип предложений',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
            ],
            options={
                'verbose_name': 'статус',
                'verbose_name_plural': 'статус',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('cr_date', models.DateField(auto_now_add=True, verbose_name='дататайм создания ')),
                ('ch_date', models.DateField(auto_now_add=True, verbose_name='дататайм изменения')),
                ('str_date', models.DateField(verbose_name='дататайм начала ротации')),
                ('stp_date', models.DateField(verbose_name='дататайм окончания ротации')),
                ('name', models.TextField()),
                ('min_w', models.IntegerField(verbose_name='мин  скоринговый балл')),
                ('max_w', models.IntegerField(verbose_name='макс скоринговый балл')),
                ('fin_user', models.ForeignKey(blank=True, help_text='кр_орг', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('types', models.ForeignKey(blank=True, help_text='тип предложения', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='lists.OfferTypes')),
            ],
            options={
                'verbose_name': 'предложение',
                'verbose_name_plural': 'предложения',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('create_date', models.DateField(auto_now_add=True, verbose_name='дата и время создания ')),
                ('change_date', models.DateField(auto_now_add=True, verbose_name='дата и время изменения')),
                ('sname', models.TextField()),
                ('fname', models.TextField()),
                ('tname', models.TextField()),
                ('b_date', models.DateField(verbose_name='дата рождения')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='номер телефона')),
                ('n_doc', models.IntegerField(verbose_name='номер паспорта')),
                ('s_we', models.IntegerField(verbose_name='скоринговый балл')),
                ('partner', models.ForeignKey(blank=True, help_text='партнер', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'анкета',
                'verbose_name_plural': 'анкеты',
                'managed': True,
            },
        ),
    ]
