# Generated by Django 3.0.5 on 2020-04-24 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='n_doc',
            field=models.IntegerField(blank=True, null=True, verbose_name='номер паспорта'),
        ),
        migrations.AlterField(
            model_name='form',
            name='s_we',
            field=models.IntegerField(blank=True, null=True, verbose_name='скоринговый балл'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='max_w',
            field=models.IntegerField(blank=True, null=True, verbose_name='макс скоринговый балл'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='min_w',
            field=models.IntegerField(blank=True, null=True, verbose_name='мин  скоринговый балл'),
        ),
    ]
